name: Deploy

on:
  push:
    branches:
      - master
      - develop

jobs:
  deploy:
    name: Deploy Serverless Functions
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master

      - name: Install Dependencies
        run: npm install

      # Develop
      - name: Deploy (devlop)
        uses: serverless/github-action@master
        if: github.ref == 'refs/heads/develop'
        with:
          args: deploy --stage develop
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      # Production
      - name: Deploy (production)
        uses: serverless/github-action@master
        if: github.ref == 'refs/heads/master'
        with:
          args: deploy --stage production
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
