name: Deployment

on:
  pull_request:
    branches:
      - master
      - develop
      - stage
    types:
      - closed

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}

jobs:
  deploy:
    if: github.event.pull_request.merged == true
    name: Deploy Serverless Functions
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master

      - name: Cache Dependencies
        id: cache
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install Dependencies
        run: npm install && SHARP_IGNORE_GLOBAL_LIBVIPS=1 npm install --arch=x64 --platform=linux sharp

      # Develop
      - name: Deploy (devlop)
        uses: serverless/github-action@master
        if: github.base_ref == 'develop'
        with:
          args: deploy --stage develop --force --verbose
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      # Stage
      - name: Deploy (stage)
        uses: serverless/github-action@master
        if: github.base_ref == 'stage'
        with:
          args: deploy --stage stage --force --verbose
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      # Production
      - name: Deploy (production)
        uses: serverless/github-action@master
        if: github.base_ref == 'master'
        with:
          args: deploy --stage production --force --verbose
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Slack Notification
        if: always()
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          author_name: serverless-file-post-processing
          fields: repo,message,commit,author,action,eventName,ref,workflow,job,took
